---
- name: Set timezone
  become: yes
  community.general.timezone:
    name: "{{ timezone }}"

- name: Check if i386 is enabled
  become: yes
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: false
  ignore_errors: true

- name: Enable i386 architecture
  become: yes
  command: dpkg --add-architecture i386
  when: result_i386_check.rc != 0

- name: Accept Steam license
  become: yes
  debconf:
    name: steamcmd
    question: steam/question
    value: "I AGREE"
    vtype: select

- name: Accept Steam license 2
  become: yes
  debconf:
    name: steamcmd
    question: steam/license
    value: ""
    vtype: note

- name: Install OS Dependencies
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 0
    state: present
    pkg:
      - curl
      - wget
      - ca-certificates
      - file
      - bsdmainutils
      - util-linux
      - python3
      - tar
      - bzip2
      - gzip
      - unzip
      - binutils
      - bc
      - jq
      - tmux
      - netcat
      - cpio
      - lib32gcc1
      - lib32stdc++6
      - steamcmd
      - libsdl2-2.0-0:i386
      - libcurl4-gnutls-dev:i386

- name: Download Node Exporter
  become: yes
  become_user: tf2server
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.1.1/node_exporter-1.1.1.linux-amd64.tar.gz
    dest: ~/
    remote_src: yes
    creates: node_exporter-1.1.1

- name: Extract Node Exporter
  become: yes
  become_user: tf2server
  command: cp ~/node_exporter-1.1.1.linux-amd64/node_exporter ~/node_exporter
  args:
    creates: ~/node_exporter

- name: Create tf2server.service
  become: yes
  copy:
    src: tf2server.service
    dest: /etc/systemd/system/tf2server.service
    mode: '644'

- name: Create prometheus.service
  become: yes
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: '644'

- name: mkdir gbans
  when: gbans
  become: yes
  become_user: tf2server
  file:
    path: ~/gbans
    state: directory
    mode: '0755'

- name: gbans download
  when: gbans
  become: yes
  become_user: tf2server
  unarchive:
    src: https://github.com/leighmacdonald/gbans/releases/download/v0.1.5/gbans--lin64.zip
    dest: ~/gbans
    remote_src: yes

- name: gbans-relay.service
  when: gbans
  become: yes
  template:
    src: gbans-relay.service.j2
    dest: /etc/systemd/system/gbans-relay.service
    mode: '644'

- name: gbans chmod
  when: gbans
  file:
    path: /home/tf2server/gbans/gbans
    mode: 0755

- name: gbans.yml
  when: gbans
  become: yes
  template:
    src: gbans.yml.j2
    dest: /home/tf2server/gbans.yml
    mode: '644'

- name: systemd reload
  become: yes
  systemd:
    daemon_reload: yes

- name: systemd enable prometheus
  become: yes
  systemd:
    name: node_exporter.service
    state: started
    enabled: yes

- name: systemd enable tf2server
  become: yes
  systemd:
    name: tf2server.service
    enabled: yes

- name: systemd enable gbans-relay
  when: gbans
  become: yes
  systemd:
    name: gbans-relay.service
    enabled: yes
    state: restarted
